openapi: 3.0.0
info:
  title: Ćevabdžinica Zmaj API
  description: REST API dokumentacija za entitet `orders`
  version: 1.0.0

servers:
  - url: http://localhost/FarisMeric/Introduction-to-Web-Programming/backend

paths:
  /orders:
    get:
      tags:
        - Orders
      summary: Vrati sve narudžbe
      responses:
        '200':
          description: Lista narudžbi
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

    post:
      tags:
        - Orders
      summary: Dodaj novu narudžbu
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Narudžba uspješno dodana

  /orders/{id}:
    get:
      tags:
        - Orders
      summary: Vrati narudžbu po ID-u
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalji narudžbe
        '404':
          description: Narudžba nije pronađena

    put:
      tags:
        - Orders
      summary: Ažuriraj narudžbu po ID-u
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Narudžba ažurirana

    delete:
      tags:
        - Orders
      summary: Obriši narudžbu po ID-u
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Narudžba obrisana

components:
  schemas:
    Order:
      type: object
      properties:
        user_id:
          type: integer
        total_price:
          type: number
          format: float
        status:
          type: string
        created_at:
          type: string
          format: date-time
